[project]
name = "tokenizer-evals"
version = "0.1.0"
description = "A package for evaluating tokenizers"
authors = [
  {email = "valentinh@allenai.org "}
]
requires-python = ">=3.9"
dependencies = [
  "datasets==3.5.0",
  "transformers==4.50.3",
  "rich==14.0.0",
  "uniseg>=0.10.0",
]

[tool.setuptools]
packages = ["src"]

[project.scripts]
eval-fertility = "src.analyze_tokenizer:main"
eval-extras = "src.instrinsic.evaluate:main"
eval-compare = "src.instrinsic.compare:main"
upload-tokenizer = "src.upload_tokenizer:main"
